In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('adres.csv', sep=";")

In [15]:
df.head(10)

                                               Адрес              Город
0  Благовещенск, Святителя Иннокентия переулок, д.17       Благовещенск
1                      Сковородино, Победы ул., д.36        Сковородино
2         Константиновка, Константиновская ул., д.40     Константиновка
3       Новокиевский Увал, 40 лет Победы улица, д.27  Новокиевский Увал
4             Благовещенск, Комсомольская улица, д.8       Благовещенск
5                          Зея, Жуковский пер., д.15                Зея
6                 Новобурейский, Советская ул., д.19      Новобурейский
7                       Райчихинск, Победы ул., д.49         Райчихинск
8                       Райчихинск, Победы ул., д.49         Райчихинск
9                Свободный, Дзержинского улица, д.49          Свободный

In [14]:
df['Город'] = df['Адрес'].apply(lambda x : x.split(',')[0])

In [28]:
city = df['Город'].unique().tolist()

['Благовещенск',
 'Сковородино',
 'Константиновка',
 'Новокиевский Увал',
 'Зея',
 'Новобурейский',
 'Райчихинск',
 'Свободный',
 'Тында',
 'Магдагачи',
 'Облучье',
 'Биробиджан',
 'Петропавловск-Камчатский',
 'Ключи',
 'Тиличики',
 'Мильково',
 'Палана',
 'Эссо',
 'Усть-Большерецк',
 'Усть-Камчатск',
 'Оссора',
 'Тигиль',
 'Соболево',
 'Вилючинск',
 'Петропавловаск-Камчатский',
 ' Ключи',
 'Паратунка',
 'Магадан',
 'Ягодное',
 'Омсукчан',
 'Палатка',
 'Ола',
 'Сусуман',
 'Сеймчан',
 'Усть-Омчуг',
 'Владивосток',
 'Вольно-Надеждинское',
 'г.Уссурийск',
 'Михайловка',
 'Уссурийск',
 'Партизанск',
 'Владимиро-Александровское',
 'Лазо',
 'Чугуевка',
 'Арсеньев',
 'Анучино',
 'Яковлевка',
 'Камень-Рыболов Ханкайского района',
 'Хороль',
 'Спасск-Дальний',
 'Дальнереченск',
 'Славянка Хасанского района',
 'Ольга',
 'Дальнегорск',
 'Лесозаводск',
 'Кировский',
 'Лучегорск',
 'Партизанск - линия электропередач',
 'Находка',
 'Артем',
 'Кировский Кировского района',
 'Санаторий имени 50-летия Октября',
 'курортный поселок Горные Ключи Кировского района',
 'Якутск',
 'Амга',
 'Батагай',
 'Бердигестях',
 'Борогонцы',
 'Вилюйск',
 'Ленск',
 'Нюрба',
 'Олекминск',
 'Покровск',
 'Сангар',
 'Усть-Нера',
 'Хандыга',
 'Черский',
 'Тикси',
 'Зырянка',
 'Депутатский',
 'Алдан',
 'Чурапча',
 'Нерюнгри',
 'лдан',
 'Южно-Сахалинск',
 'Томари',
 'Южно-Курильск',
 'Углегорск',
 'Курильск',
 'Северо-Курильск',
 'Холмск',
 'Поронайск',
 'Долинск',
 'Тымовское',
 'Оха',
 'Александровск-Сахалинский',
 'Макаров',
 'Ноглики.',
 'Корсаков',
 'Смирных',
 'Хабаровск',
 'Чегдомын',
 'Советская Гавань',
 'Комсомольск-на-Амуре',
 ' Хабаровск',
 'Троицкое',
 'абаровск',
 'Хабаровская Банковская школа (колледж)',
 'Анадырь',
 'Тавайваам',
 'Певек',
 'Лаврентия',
 'Провидения',
 'Эгвекинот',
 'Беринговский',
 'Иультинский',
 'Билибино']

In [36]:
gorod = 'Алдан'
df.query(f'Город == "{gorod}"')['Адрес'].tolist()

['Алдан, 10 лет Якутии, 31а', 'Алдан, 10 лет Якутии, 31а']